// Generated Retrofit API Client
// This file is auto-generated by the api_gen Retrofit code generator created by @Christian Onyisi.

import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'coincap_api_models.dart';

part 'coincap_api_client.g.dart';

/// Coincap OpenAPI Client (Production-Ready)
@RestApi(baseUrl: "https://rest.coincap.io")
abstract class CoinCapApiClient {
  factory CoinCapApiClient(Dio dio, {String baseUrl}) = _CoinCapApiClient;

  /// Retrieve a list of assets
  @GET("/v2/assets")
  Future<HttpResponse<AssetsListResponse>> getAssets(
    @Queries() AssetsQuery query,
  );

  /// Retrieve a single asset
  @GET("/v3/assets/{slug}")
  Future<HttpResponse<AssetsListResponse>> getAssetBySlug(
    @Path("slug") String slug,
  );

  /// Retrieve markets for a specific asset
  @GET("/v3/assets/{slug}/markets")
  Future<HttpResponse<AssetsListResponse>> getMarketsBySlug(
    @Path("slug") String slug,
    @Queries() MarketsQuery query,
  );

  /// Retrieve historical data for a specific asset
  @GET("/v3/assets/{slug}/history")
  Future<HttpResponse<AssetsListResponse>> getHistoriesBySlug(
    @Path("slug") String slug,
    @Queries() HistoryQuery query,
  );

  /// Retrieve a list of exchanges
  @GET("/v3/exchanges")
  Future<HttpResponse<AssetsListResponse>> getExchanges(
    @Queries() ExchangesQuery query,
  );

  /// Retrieve details for a specific exchange
  @GET("/v3/exchanges/{exchange}")
  Future<HttpResponse<AssetsListResponse>> getExchangeByExchange(
    @Path("exchange") String exchange,
  );

  /// Retrieve a list of markets
  @GET("/v3/markets")
  Future<HttpResponse<AssetsListResponse>> getMarkets(
    @Queries() MarketsQuery query,
  );

  /// Retrieve conversion rates
  @GET("/v3/rates")
  Future<HttpResponse<AssetsListResponse>> getRates(@Query("ids") String? ids);

  /// Retrieve a conversion rate by slug
  @GET("/v3/rates/{slug}")
  Future<HttpResponse<RateResponse>> getRateBySlug(@Path("slug") String slug);
}

/// Create configured API client with interceptors
CoinCapApiClient createCoinCapApiClient() {
  final dio = Dio();
  // Add interceptors
  dio.interceptors.add(LogInterceptor(requestBody: true, responseBody: true));

  return CoinCapApiClient(dio);
}
