// Generated API Library
// This file is auto-generated by the api_gen Retrofit code generator created by @Christian Onyisi.

library;

export 'coincap_api_client.dart';
export 'coincap_api_models.dart';
