// Generated Freezed Models
// This file is auto-generated by the api_gen Retrofit code generator created by @Christian Onyisi.
// ignore_for_file: invalid_annotation_target


import 'package:freezed_annotation/freezed_annotation.dart';

part 'coincap_api_models.freezed.dart';
part 'coincap_api_models.g.dart';


/// Convert String to DateTime (nullable)
DateTime? _dateTimeFromJson(String? json) => json == null ? null : DateTime.parse(json);

/// Convert String to DateTime (required)
DateTime _dateTimeFromJsonRequired(String json) => DateTime.parse(json);

/// Convert DateTime to String (nullable)
String? _dateTimeToJson(DateTime? dateTime) => dateTime?.toIso8601String();

/// Convert DateTime to String (required)
String _dateTimeToJsonRequired(DateTime dateTime) => dateTime.toIso8601String();

/// Convert List<String> to List<DateTime> (nullable)
List<DateTime>? _dateTimeListFromJson(List<String>? json) => json?.map((s) => DateTime.parse(s)).toList();

/// Convert List<String> to List<DateTime> (required)
List<DateTime> _dateTimeListFromJsonRequired(List<String> json) => json.map((s) => DateTime.parse(s)).toList();

/// Convert List<DateTime> to List<String> (nullable)
List<String>? _dateTimeListToJson(List<DateTime>? dateTimeList) => dateTimeList?.map((dt) => dt.toIso8601String()).toList();

/// Convert List<DateTime> to List<String> (required)
List<String> _dateTimeListToJsonRequired(List<DateTime> dateTimeList) => dateTimeList.map((dt) => dt.toIso8601String()).toList();

@Freezed()
sealed class ResponseModelDataItem with _$ResponseModelDataItem {
  const factory ResponseModelDataItem({
    String? id,
    String? rank,
    String? symbol,
    String? name,
    String? supply,
    @JsonKey(name: "maxSupply")
    String? maxsupply,
    @JsonKey(name: "marketCapUsd")
    String? marketcapusd,
    @JsonKey(name: "volumeUsd24Hr")
    String? volumeusd24hr,
    @JsonKey(name: "priceUsd")
    String? priceusd,
    @JsonKey(name: "changePercent24Hr")
    String? changepercent24hr,
    @JsonKey(name: "vwap24Hr")
    String? vwap24hr,
    String? explorer,
  }) = _ResponseModelDataItem;

  factory ResponseModelDataItem.fromJson(Map<String, dynamic> json) => _$ResponseModelDataItemFromJson(json);
}


typedef ResponseModelData = List<ResponseModelDataItem>;

@Freezed()
sealed class AssetsListResponse with _$AssetsListResponse {
  const factory AssetsListResponse({
    int? timestamp,
    ResponseModelData? data,
  }) = _AssetsListResponse;

  factory AssetsListResponse.fromJson(Map<String, dynamic> json) => _$AssetsListResponseFromJson(json);
}


@Freezed()
sealed class ServerError with _$ServerError {
  const factory ServerError({
    required String error,
    required String message,
    @JsonKey(name: "statusCode")
    required double statuscode,
  }) = _ServerError;

  factory ServerError.fromJson(Map<String, dynamic> json) => _$ServerErrorFromJson(json);
}


@Freezed()
sealed class NotFoundError with _$NotFoundError {
  const factory NotFoundError({
    String? error,
    int? timestamp,
  }) = _NotFoundError;

  factory NotFoundError.fromJson(Map<String, dynamic> json) => _$NotFoundErrorFromJson(json);
}


@Freezed()
sealed class ResponseModel1DataItem with _$ResponseModel1DataItem {
  const factory ResponseModel1DataItem({
    @JsonKey(name: "exchangeId")
    String? exchangeid,
    @JsonKey(name: "baseId")
    String? baseid,
    @JsonKey(name: "quoteId")
    String? quoteid,
    @JsonKey(name: "baseSymbol")
    String? basesymbol,
    @JsonKey(name: "quoteSymbol")
    String? quotesymbol,
    @JsonKey(name: "volumeUsd24Hr")
    String? volumeusd24hr,
    @JsonKey(name: "priceUsd")
    String? priceusd,
    @JsonKey(name: "volumePercent")
    String? volumepercent,
  }) = _ResponseModel1DataItem;

  factory ResponseModel1DataItem.fromJson(Map<String, dynamic> json) => _$ResponseModel1DataItemFromJson(json);
}


@Freezed()
sealed class ResponseModel2DataItem with _$ResponseModel2DataItem {
  const factory ResponseModel2DataItem({
    @JsonKey(name: "priceUsd")
    String? priceusd,
    int? time,
    @JsonKey(name: "date", fromJson: _dateTimeFromJson, toJson: _dateTimeToJson)
    DateTime? date,
  }) = _ResponseModel2DataItem;

  factory ResponseModel2DataItem.fromJson(Map<String, dynamic> json) => _$ResponseModel2DataItemFromJson(json);
}


@Freezed()
sealed class ResponseModel3DataItem with _$ResponseModel3DataItem {
  const factory ResponseModel3DataItem({
    @JsonKey(name: "exchangeId")
    String? exchangeid,
    String? name,
    String? rank,
    @JsonKey(name: "percentTotalVolume")
    String? percenttotalvolume,
    @JsonKey(name: "volumeUsd")
    String? volumeusd,
    @JsonKey(name: "tradingPairs")
    String? tradingpairs,
    bool? socket,
    @JsonKey(name: "exchangeUrl")
    String? exchangeurl,
    int? updated,
  }) = _ResponseModel3DataItem;

  factory ResponseModel3DataItem.fromJson(Map<String, dynamic> json) => _$ResponseModel3DataItemFromJson(json);
}


@Freezed()
sealed class ValidationError with _$ValidationError {
  const factory ValidationError({
    String? error,
  }) = _ValidationError;

  factory ValidationError.fromJson(Map<String, dynamic> json) => _$ValidationErrorFromJson(json);
}


@Freezed()
sealed class ResponseModel5DataItem with _$ResponseModel5DataItem {
  const factory ResponseModel5DataItem({
    @JsonKey(name: "exchangeId")
    String? exchangeid,
    String? rank,
    @JsonKey(name: "baseSymbol")
    String? basesymbol,
    @JsonKey(name: "baseId")
    String? baseid,
    @JsonKey(name: "quoteSymbol")
    String? quotesymbol,
    @JsonKey(name: "quoteId")
    String? quoteid,
    @JsonKey(name: "priceQuote")
    String? pricequote,
    @JsonKey(name: "priceUsd")
    String? priceusd,
    @JsonKey(name: "volumeUsd24Hr")
    String? volumeusd24hr,
    @JsonKey(name: "percentExchangeVolume")
    String? percentexchangevolume,
    @JsonKey(name: "tradesCount24Hr")
    String? tradescount24hr,
    int? updated,
  }) = _ResponseModel5DataItem;

  factory ResponseModel5DataItem.fromJson(Map<String, dynamic> json) => _$ResponseModel5DataItemFromJson(json);
}


@Freezed()
sealed class ResponseModel6DataItem with _$ResponseModel6DataItem {
  const factory ResponseModel6DataItem({
    String? id,
    String? symbol,
    @JsonKey(name: "currencySymbol")
    String? currencysymbol,
    String? type,
    @JsonKey(name: "rateUsd")
    String? rateusd,
  }) = _ResponseModel6DataItem;

  factory ResponseModel6DataItem.fromJson(Map<String, dynamic> json) => _$ResponseModel6DataItemFromJson(json);
}


@Freezed()
sealed class RateResponse with _$RateResponse {
  const factory RateResponse({
    int? timestamp,
  }) = _RateResponse;

  factory RateResponse.fromJson(Map<String, dynamic> json) => _$RateResponseFromJson(json);
}


@Freezed()
sealed class AssetsQuery with _$AssetsQuery {
  const factory AssetsQuery({
    String? search,
    String? ids,
    dynamic limit,
    dynamic offset,
  }) = _AssetsQuery;

  factory AssetsQuery.fromJson(Map<String, dynamic> json) => _$AssetsQueryFromJson(json);
}


@Freezed()
sealed class MarketsQuery with _$MarketsQuery {
  const factory MarketsQuery({
    dynamic limit,
    dynamic offset,
  }) = _MarketsQuery;

  factory MarketsQuery.fromJson(Map<String, dynamic> json) => _$MarketsQueryFromJson(json);
}


@Freezed()
sealed class HistoryQuery with _$HistoryQuery {
  const factory HistoryQuery({
    required String interval,
    dynamic start,
    dynamic end,
  }) = _HistoryQuery;

  factory HistoryQuery.fromJson(Map<String, dynamic> json) => _$HistoryQueryFromJson(json);
}


@Freezed()
sealed class ExchangesQuery with _$ExchangesQuery {
  const factory ExchangesQuery({
    dynamic limit,
    dynamic offset,
  }) = _ExchangesQuery;

  factory ExchangesQuery.fromJson(Map<String, dynamic> json) => _$ExchangesQueryFromJson(json);
}


